services:
  - type: web
    name: fullstack-socket-app
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free